### ISSUE TITLE
crash when locking screen

### ISSUE THREAD

**Issue by mailinglists35** [ginsudev/YTMusicUltimate#1]
scrnario:

open app
play something
lock screen using power button

result: plays about 10 seconds then crashes

doesn't crash if I swipe up to home screen and allow device to sleep on display inactivity

crash log: https://www.pastefile.com/cyf8nn

**Comment by mailinglists35** [comment]
also crashes when returning to app then locking the screen while in app

**Comment by ginsudev** [comment]
Hi, for some reason I didn't receive a notification that you opened this issue. Could you please post the crash log again? Thanks.

**Comment by kalashjain72** [comment]
what is latest version

**Comment by JimmyMercer217** [comment]
Having the same problem. It has ruined enjoyments of music.

**Comment by luvvvdev** [comment]
Same problem
