### ISSUE TITLE
Feature Request:unlimited skips

### ISSUE THREAD

**Issue by ChrisRyan400** [ginsudev/YTMusicUltimate#100]

**Comment by dayanch96** [comment]
allow me to guess, are you using Signulous?

**Comment by ChrisRyan400** [comment]
No, I install with troll store …iPhone 11 Pro , iOS 15.1.1

**Comment by dayanch96** [comment]
can you share screen record by any chance?

**Comment by dayanch96** [comment]
Re-open if you’ll have questions
