### ISSUE TITLE
[Feature Request] Remove song from playlist button

### ISSUE THREAD

**Issue by b-risk** [ginsudev/YTMusicUltimate#101]
Because youtube won't (post is 4 years old but still accurate)
![firefox_BbC7umDxIu](https://github.com/ginsudev/YTMusicUltimate/assets/89107446/e93e49b8-2bcf-434a-9b1a-f5af0a123951)

To be clear, i'm talking about a button that you can click well listening to a song that would remove the song from the playlist well letting you finish it like in the regular youtube app somewhere like this
![image](https://github.com/ginsudev/YTMusicUltimate/assets/89107446/d0dc4e3e-66a4-4328-a350-ad2bc6adb92f)

The left swipe to "remove" under the song is NOT the same thing and doesn't actually remove the song from the playlist it will just skip it and not play during your current listen
The only way to remove a song from a playlist is by unintuitively scrolling through the entire playlist until you find the song to find the 3 dots you click and remove from the playlist

**Comment by dayanch96** [comment]
You already have this button in playlist - not in queue.

**Comment by b-risk** [comment]
> You already have this button in playlist - not in queue.

as i mentioned it is unintuitive and takes a while because i have a large playlist, it would be much easier to just have a button that’s on the song itself instead scrolling through it all

**Comment by b-risk** [comment]
> you are trying to add it to queue - as i said before. queue and app wont know in which of your playlist this music is, since it just use it as link.

i think i understand, so you’re saying when i use playlists it’s not actually using the playlist but a custom queue so there’s no way to add it?

**Comment by b-risk** [comment]
> its queue based on your playlist, but not your playlist

alright, thanks for the info!
