### ISSUE TITLE
YTMusic is unavailable in your country

### ISSUE THREAD

**Issue by birdfly** [ginsudev/YTMusicUltimate#103]
I just installed the newest version , I got a message from the homescreen said that "YTMusic is unavailable in your country" after I  logged in my Google Account. I am from China ,of course all youtube services are blocked by GFW ,so I use VPN(Cloudflare Warp+) to surf the internet .In my knowndge ,if I visit Youtube service with China IP ,I would not access the service at all ,but if I visit it with Not-China IP ,why I got this message .

Or is there any way to remove the country restrictions？

Thanks for your efforts

**Comment by dayanch96** [comment]
Problem in your VPN/Proxy
