### ISSUE TITLE
Can't login in on ios 15

### ISSUE THREAD

**Issue by spectr0m** [ginsudev/YTMusicUltimate#106]
keeps saying google couldn't verify if it's safe

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/issues/84

**Comment by dayanch96** [comment]
@spectr0m fixed in latest release: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.0

**Comment by cutzz1** [comment]
> @spectr0m fixed in latest release: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.0

@dayanch96 still getting same error in iOS 15

**Comment by cutzz1** [comment]
> @cutzz1 try again, but after first attept close safari window and tap to sign in again

didn't work, but installing 1.3.9 worked
