### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JackPlaysGames0510** [ginsudev/YTMusicUltimate#109]
When you like a video it bugs out the previous and next buttons
![image](https://github.com/ginsudev/YTMusicUltimate/assets/48178959/68d5aead-906f-4ca9-91a7-d548527a6d5d)

**Comment by dayanch96** [comment]
turn off seek buttons in the settings and restart app. this glitch will be fixed in the next update

**Comment by JackPlaysGames0510** [comment]
Ok thanks man

**Comment by JackPlaysGames0510** [comment]
Still dose it

**Comment by dayanch96** [comment]
can you send screen record?

**Comment by JackPlaysGames0510** [comment]
Uploading RPReplay_Final1684159803.mp4…

**Comment by JackPlaysGames0510** [comment]
https://github.com/ginsudev/YTMusicUltimate/assets/48178959/fda25310-433a-4c87-91f9-c8d6070511dc

**Comment by dayanch96** [comment]
oh, i see. thanks

**Comment by dayanch96** [comment]
reuploaded. take a look @JackPlaysGames0510

**Comment by JackPlaysGames0510** [comment]
ok will do

**Comment by JackPlaysGames0510** [comment]
it works now
