### ISSUE TITLE
Yt music crashing

### ISSUE THREAD

**Issue by Elico0** [ginsudev/YTMusicUltimate#11]
Whenever I play a song, after like 10 songs it stops to play and exits from the app by itself.

**Comment by ElSigmaTom** [comment]
I've never encountered that issue but what I do encounter is it crashes when minimized/home button is pressed while playing a song or when I lock the phone.

**Comment by ginsudev** [comment]
Let me know if it's fixed in the latest version :)

**Comment by patkozlowski** [comment]
Seems to be fixed on jailed devices on v1.1.9.  Will keep retesting and report back if any issues.  Great job!
