### ISSUE TITLE
Request new features to remove this

### ISSUE THREAD

**Issue by JackPlaysGames0510** [ginsudev/YTMusicUltimate#110]
![image](https://github.com/ginsudev/YTMusicUltimate/assets/48178959/83ca8ea6-ca08-4ca2-a826-0336ab1473f2)

**Comment by dayanch96** [comment]
I'll take a look. But i think its better keep it only on its position and not pin to the upper side of the screen. thats the safest method

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.3.9

**Comment by JackPlaysGames0510** [comment]
Ok thanks
