### ISSUE TITLE
No label bug

### ISSUE THREAD

**Issue by JackPlaysGames0510** [ginsudev/YTMusicUltimate#111]
https://github.com/ginsudev/YTMusicUltimate/assets/48178959/6d4b5069-c2a9-4e42-8275-6653d1aa0997

**Comment by dayanch96** [comment]
device? can you send full video?

**Comment by JackPlaysGames0510** [comment]
iPhone 12 Pro Max

**Comment by JackPlaysGames0510** [comment]
I’m having trouble sending the vid

**Comment by JackPlaysGames0510** [comment]
https://mega.nz/file/x5dhzLbT#KuYkPSl51QBCKI7qvksvF_GyOqT7RCN51gKTI8ac42g

**Comment by dayanch96** [comment]
@JackPlaysGames0510 please test re-uploaded ipa and let me know if it fixed

**Comment by JackPlaysGames0510** [comment]
Ok will do

**Comment by JackPlaysGames0510** [comment]
The ipa it’s not modded

**Comment by JackPlaysGames0510** [comment]
Still doing the same thing

**Comment by dayanch96** [comment]
are you using ipa from releases page or trying to inject it manually first?

**Comment by JackPlaysGames0510** [comment]
The ipa on the website

**Comment by dayanch96** [comment]
weird. tested on iphone 7, 11, two 13 pro max and no problems

**Comment by JackPlaysGames0510** [comment]
Huh wired

**Comment by JackPlaysGames0510** [comment]
Can this be fix then

**Comment by dayanch96** [comment]
> Can this be fix then

What do you mean?

**Comment by JackPlaysGames0510** [comment]
The no label still needs to be fix

**Comment by dayanch96** [comment]
I will if reproduce your problem

**Comment by JackPlaysGames0510** [comment]
ok thanks

**Comment by dayanch96** [comment]
Fixed in the latest release: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.1

Thanks for your support!
