### ISSUE TITLE
Audio mode in automatic playlists and albums

### ISSUE THREAD

**Issue by ciro97RM** [ginsudev/YTMusicUltimate#114]
When I listen an album or a playlist, the app only plays the video version of the songs. Is it possible to add the feature that let me play the audio version? When I tried the YouTube music premium version the app let me play the songs instead of videos.
Thanks a lot for your work.

**Comment by JackPlaysGames0510** [comment]
Go to player options and go to default playback mode and change it to the music note

**Comment by ciro97RM** [comment]
It doesn’t work Inviato da iPhoneIl giorno 20 mag 2023, alle ore 14:04, Jacks_Cracks ***@***.***> ha scritto:﻿
Go to player options and go to default playback mode and change it to the music note

**Comment by dayanch96** [comment]
i assume it depends on region where you using it, so using VPN can help you. on my side it works as expected in playlists and albums
