### ISSUE TITLE
Cant login to google

### ISSUE THREAD

**Issue by WintechX** [ginsudev/YTMusicUltimate#118]
error: This app is unsafe

**Comment by WintechX** [comment]
Doesnt work.

**Comment by WintechX** [comment]
Could you reinstall the app to see if it works for you?

**Comment by dayanch96** [comment]
Maybe something added in latest version then, can you try previous version?

**Comment by WintechX** [comment]
i tried previous, even tried one from appdb thats really old, same issue.

**Comment by dayanch96** [comment]
got you. ill let you know if can fix it

**Comment by WintechX** [comment]
thanks mate, let me know if its fixed. :D

**Comment by QELiTHiUm** [comment]
The same problem here. Can't login, even tried the video, with no luck.

**Comment by malofius** [comment]
the same problem, through altstore gives an error, and through sideloadly everything is OK

**Comment by malofius** [comment]
I will wait for a solution to the problem because it is more altstore convenient

**Comment by dayanch96** [comment]
Just wait for update

**Comment by dayanch96** [comment]
Here you go: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.1

Trick still the same:
1. Tap to Sign in
2. Wait for a second and close authorization window
3. Tap to Sign in again.

**Comment by malofius** [comment]
> Вот так: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.1
> 
> Трюк остается прежним:
> 
> 1. Нажмите, чтобы войти
> 2. Подождите секунду и закройте окно авторизации
> 3. Нажмите, чтобы войти снова.

yes, it works, thanks

**Comment by QELiTHiUm** [comment]
it works for me now too. (Sideloadly, iPadOs 15,7,6)

**Comment by petriefka** [comment]
> Here you go: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.1
> 
> Trick is still the same:
> 
> 1. Tap to Sign in
> 2. Wait for a second and close authorization window
> 3. Tap to Sign in again.

I do the steps but after i close the window and opened again the app just crash and get closed
