### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by Gujdys** [ginsudev/YTMusicUltimate#120]
Hi, i just have problem that when i start the app, tap on log in and than when i tap on that form where you put your email, the app just crash. Any ideas for fixing it ? thanks

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/issues/118

**Comment by Gujdys** [comment]
- I tried it but still doing this.  I try reinstall, older version, newest version and still nothing..

**Comment by dayanch96** [comment]
can you send screen record?

**Comment by Gujdys** [comment]
https://github.com/ginsudev/YTMusicUltimate/assets/94970551/a0edb2a5-47b6-4d65-95d4-c8b12af5dff1

**Comment by dayanch96** [comment]
ios 17?

**Comment by Gujdys** [comment]
Yes is this that problem ? 🥲

**Comment by dayanch96** [comment]
Obviously. My current workaround conflicts with UI so i use delays to activate it. And I cant test it on iOS 17 and have no desire to, tbh😁

**Comment by dayanch96** [comment]
Oh, I can suggest you to try enter mail when you open login window for the first time. Yes, you still can’t enter but your keyboard view already loaded so it shouldnt crash when you open it for the second time

**Comment by Gujdys** [comment]
When i open it every time the form is going to be loaded but kexboard doesnt show up. Si i try to enter the email with copy and paste. Sometime it worked but the password form is not loaded and need to be clicked on it so i cant do it this way. 🥲😬

**Comment by Gujdys** [comment]
does it gonna work on 16.5 IOS ?

**Comment by dayanch96** [comment]
> does it gonna work on 16.5 IOS ?

It should

**Comment by Gujdys** [comment]
yup i work. thanks for the help and this app. <3
