### ISSUE TITLE
Asking for Login everytime I open the app after v1.1.7

### ISSUE THREAD

**Issue by iammanpreetsingh** [ginsudev/YTMusicUltimate#13]
https://github.com/ginsudev/YTMusicUltimate/issues/12

After adding this in 1.1.7, I have to login into my Google Account each time I open the app. I will have to use v1.1.6 unfortunately. 

YouTube Music: v5.21.1
YTMusicUltimate: v1.1.17
Device: iPhone 8
iOS: 14.8 Jailed

**Comment by c12n** [comment]
> https://github.com/ginsudev/YTMusicUltimate/issues/12
> 
> 
> 
> After adding this in 1.1.7, I have to login into my Google Account each time I open the app. I will have to use v1.1.6 unfortunately. 
> 
> 
> 
> YouTube Music: v5.21.1
> 
> YTMusicUltimate: v1.1.17
> 
> Device: iPhone 8
> 
> iOS: 14.8 Jailed

Did you add ytsideloadfix & ytloginfix dylib to the ipa? - SultanMods

**Comment by iammanpreetsingh** [comment]
> > #12
> > After adding this in 1.1.7, I have to login into my Google Account each time I open the app. I will have to use v1.1.6 unfortunately.
> > YouTube Music: v5.21.1
> > YTMusicUltimate: v1.1.17
> > Device: iPhone 8
> > iOS: 14.8 Jailed
> 
> Did you add ytsideloadfix & ytloginfix dylib to the ipa? - SultanMods

Yes. 
I tried with YTMusicUltimate.dylib, YTSideloadFix.dylib and YTLoginFix.dylib
then 
I also tried YTMusicUltimate.dylib and YTSideloadFix.dylib
then
I also tried YTMusicUltimate.dylib only.

All were giving me the same issues. So it must be YTMusicUltimate.dylib that is causing that.

**Comment by ginsudev** [comment]
I haven't updated the code to support v5.21+, Google changed some things that I need to sort out. For now, you can use YTMusicUltimate v1.1.8 iPA in the Releases section.
