### ISSUE TITLE
Latest version v1.5 can not be installed using XCode/IPA App Signer

### ISSUE THREAD

**Issue by ttyman0109a** [ginsudev/YTMusicUltimate#130]
Latest version v1.5 can not be installed using XCode/IPA App Signer.

I get the "cannot install app" message when I tried to install the app using XCode.

Previous version v1.4 works.

**Comment by dayanch96** [comment]
This is literally same IPA type as the previous one. Nothing in the ipa extraction method has changed.

**Comment by ttyman0109a** [comment]
I guess I tried to install the new one over the old one and it failed.  I deleted the old one and re-install and it now works.
