### ISSUE TITLE
Application login problem

### ISSUE THREAD

**Issue by D1mar0n** [ginsudev/YTMusicUltimate#131]
Hello! Installed the app using Sideloadly.
I open the application and enter the email address of my account, but I receive a notification that the integrity of the application cannot be verified and login to the account is blocked.
How to solve this problem and run the application?

**Comment by dayanch96** [comment]
for example, by looking for previous similar issues before creating a new one: https://github.com/ginsudev/YTMusicUltimate/issues/115

**Comment by D1mar0n** [comment]
I apologize for not reading all the problems described earlier. It really solved the problem. Thank you for your help!Отправлено с iPhone22 авг. 2023 г., в 18:57, Dan ***@***.***> написал(а):﻿
for example, by looking for previous similar issues before creating a new one: #115

**Comment by dayanch96** [comment]
All good, glad it worked
