### ISSUE TITLE
Disable videos?

### ISSUE THREAD

**Issue by amithunter** [ginsudev/YTMusicUltimate#134]
There is no real option of disabling the music videos from playing. 
Even when it’s on music priority mode in the settings. 

When I choose a song from the most listened list - it's playing the actual music and not the music video.
If I choose the same song from the album itself - it's playing the music video.

What can I do?

**Comment by dayanch96** [comment]
i guess settings bit glitchy, select audio and then video mode again and restart app

**Comment by dayanch96** [comment]
re-open if you'll have any questions

**Comment by amithunter** [comment]
> re-open if you'll have any questions

it's still not working.
