### ISSUE TITLE
[Issue] Can't download music

### ISSUE THREAD

**Issue by TomHarro** [ginsudev/YTMusicUltimate#15]
Download button does not do anything and does not save to storage.

**Comment by ginsudev** [comment]
Haven't had time to work on offline listening yet. Maybe soon

**Comment by ttuleyb** [comment]
Is this even possible? I have yet to see a single other music ipa that can download music internally

**Comment by ginsudev** [comment]
> Is this even possible? I have yet to see a single other music ipa that can download music internally

I've already got it half working on my device, so I'd assume so

**Comment by N04-Git** [comment]
It would be really cool for me to be able to listen music offline cuz I don't have internet except in my house, so it would be really cool if you was able to add it 💙🔥🔥👋✌️

**Comment by huantianad** [comment]
Hi, just wanted to ask if this is something still being worked on? Not a super easy feature so I assume it’s been stalled

**Comment by akaROOSTA** [comment]
hey dev
just wanna say thanks for your hard work on making these cool and desperately needed tweaks and i really appreciate the time you put into these... i can only imagine how much hard work and the gallons of coffee you must endure 

anyways friend... have an awesome day

**Comment by MasqueradeX45** [comment]
Being able to download music would be nice

**Comment by akaROOSTA** [comment]
> Haven't had time to work on offline listening yet. Maybe soon

I notice your tweak isn't the only one to hang up that section. Is there a legal issue as to why???

I notice that the Spotify tweaks for premium membership but they don't have the download for offline listening also
