### ISSUE TITLE
Keeps on showing video when I have it on music sign 

### ISSUE THREAD

**Issue by Robbiecookie** [ginsudev/YTMusicUltimate#150]
I have the default playback mode on the music sign but it still keeps on playing the video

**Comment by dayanch96** [comment]
try to select video mode and audio mode back and check if it works

**Comment by Robbiecookie** [comment]
It still ain’t working. I tried it multiple times and there was not a single change

**Comment by Robbiecookie** [comment]
I did it again it still isn’t working can y’all fix it?

**Comment by dayanch96** [comment]
it works on both my devices. no idea what you’re doing and why it doesnt work

**Comment by Robbiecookie** [comment]
I changed the default playback mode to the music sign, then did the restart the app to apply the changes, and then when I went back into the app it still showed the music videos rather then the song

**Comment by Robbiecookie** [comment]
Still ain’t working I’ve tried many more times yet it doesr change anything

**Comment by Robbiecookie** [comment]
Do you know anyway I could fix it? I’ve redownloaded it multiple times and it still doesn’t work

**Comment by dayanch96** [comment]
Sorry still can't reproduce it. Are you sure that problem not on your side?

**Comment by Robbiecookie** [comment]
I can’t tell, what do you mean by that it’s a problem on my side?

**Comment by Robbiecookie** [comment]
, I used Sideloadly v.0.50.3, I’m on iOS 17.3, and I’m in the USA

**Comment by TmanGamer** [comment]
The same thing is happening to me

**Comment by TmanGamer** [comment]
I’m on iOS 16.7.2 on an iPhone 8 (10,4) and am using the latest version of altstore

**Comment by dayanch96** [comment]
try latest release

**Comment by dayanch96** [comment]
Reopen if issue not fixed

**Comment by Robbiecookie** [comment]
It still doesn’t work

**Comment by Robbiecookie** [comment]
Is there anything new I could try? I’ve downloaded the most recent file yet it still doesn’t work
