### ISSUE TITLE
Warning: Login info

### ISSUE THREAD

**Issue by aaronliu0130** [ginsudev/YTMusicUltimate#153]
I’m trying to learn Spanish so I set my system to it. I also just sideloaded this app today. After doing the login workaround (huh…), I am greeted with this:
![IMG_2367](https://github.com/ginsudev/YTMusicUltimate/assets/11874211/50b1de67-a494-4b33-9d31-e93f97afd79a)
If you press OK, the app crashes. If you press cancel, you can proceed to brand account select normally and then get another pop-up that’s exactly the same and behavior. After pressing cancel again, the pop-up never bothers you again. Any idea why this happens?

**Comment by dayanch96** [comment]
"WARNING" = "Advertencia";
"LOGIN_INFO" = "Es necesario reiniciar la aplicación después de iniciar sesión correctamente en la cuenta de Google";
