### ISSUE TITLE
“Google couldn't confirm this attempt to sign in is safe. If you think this is a mistake, you can close and try again to sign in”

### ISSUE THREAD

**Issue by Reksely** [ginsudev/YTMusicUltimate#161]
When I try to sign in with my account it just gives this error. I have tried using some kind of workrounds yet none worked. Is there any fix? (I used sideloadly without jailbreak)

**Comment by dayanch96** [comment]
have you tried this?

https://github.com/ginsudev/YTMusicUltimate/issues/115

**Comment by hyyz17200** [comment]
> have you tried this?
> 
> #115

I have the same issue and it works for me! I am sideloaded without jailbreak too!

**Comment by unwdbw** [comment]
i got you i have a solution for this go to ---   settings>passwords -- add a new password by clicking + icon on right upper corner 
website - google.com
user name - ( your gmail )
and type your password 
again go sing in page in youtube mod when you will be directed to sing in page a keyboard popup will appear ( use ----.gmail.com ) boom you bypassed not safe login page
