### ISSUE TITLE
Premium Features no longer work 

### ISSUE THREAD

**Issue by Cha0sMaid** [ginsudev/YTMusicUltimate#163]
All ads are still gone and background play still works, but I'm only allowed to use radio I cant listen to individual songs. Could it have anything to do with the fact that i had a subscription to YouTube music 2 years ago? It did work for a short time after first install but now it no longer works even after reinstalling or using a different google account.

**Comment by Bassaw1** [comment]
Offline download does not also work after I reinstalled the app.

**Comment by dayanch96** [comment]
> Offline download does not also work after I reinstalled the app.

it doesn’t work without premium unless you got luck

**Comment by Cha0sMaid** [comment]
My issue is only for Canadian users turns out. but changing the app version to 4.27.53 in Sideloadly fixes the issue.

**Comment by dayanch96** [comment]
> My issue is only for Canadian users turns out. but changing the app version to 4.27.53 in Sideloadly fixes the issue.

Just changed version in info.plist?

**Comment by Blockr22** [comment]
Another Canada user here @Cha0sMaid  @dayanch96 . Have tried changing app version mentioned above via Sideloadly but still don’t have unlimited skips & can’t choose songs. What can i do to make it work ?
