### ISSUE TITLE
app force close

### ISSUE THREAD

**Issue by henrietta2243** [ginsudev/YTMusicUltimate#169]
the app won't open, it always close it self

**Comment by dayanch96** [comment]
crashlog?

**Comment by henrietta2243** [comment]
[YouTubeMusic-2024-01-15-211753.ips.zip](https://github.com/ginsudev/YTMusicUltimate/files/13952018/YouTubeMusic-2024-01-15-211753.ips.zip)
 crash  log

**Comment by dayanch96** [comment]
try latest release

**Comment by henrietta2243** [comment]
Yes sir

**Comment by dayanch96** [comment]
fixed or same issue?

**Comment by henrietta2243** [comment]
Crash fixed, thanks
I’ll close this issue
