### ISSUE TITLE
Crash when locking screen/going to home

### ISSUE THREAD

**Issue by sonicshin** [ginsudev/YTMusicUltimate#17]
Hi, thank you for the wonderful ipa.
I have just one problem.
When I lock the phone/go to the home screen once, the app rarely crashes. (5%)
But when I turn on my phone/re-open the app and then lock my phone/go to the home screen again, the app crashes 100%.

It isn’t a complete crash since I can see the app in the multitask screen(double clicking home button), but the music stops and when I re-open the app, the music progress is reset.

**Comment by ElSigmaTom** [comment]
I have to agree with this, unfortunately even after the latest update, the issue still persists.

**Comment by ginsudev** [comment]
The issue only happens when sideloaded with anything other than TrollStore. I am still yet to figure out why this happens only when sideloaded and not when installed as a tweak on jailbroken devices.

**Comment by ElSigmaTom** [comment]
I see, I am using an iP7 (15.6), I've sideloaded the IPA using sideloadly.

**Comment by ginsudev** [comment]
> I see, I am using an iP7 (15.6), I've sideloaded the IPA using sideloadly. 

Does the latest iPA v1.1.9 still have the issue?

**Comment by sonicshin** [comment]
I just tested v1.1.9, and I think the fake premium isn't applied properly.
I'm getting ads and background play doesn't work at all.

**Comment by ginsudev** [comment]
> I just tested v1.1.9, and I think the fake premium isn't applied properly.
> 
> I'm getting ads and background play doesn't work at all.

Go to YTMusicUltimate settings and re-enable everything

**Comment by sonicshin** [comment]
> Go to YTMusicUltimate settings and re-enable everything

Oh sorry that was dumb of me.
I tested it for 10 minutes and it didn’t crash at all!
Thanks for the fix.
