### ISSUE TITLE
Error building with SIDELOADING=1

### ISSUE THREAD

**Issue by binnichtaktiv** [ginsudev/YTMusicUltimate#170]
When I tro to build with 'make clean package SIDELOADING=1' I get this error
![image](https://github.com/ginsudev/YTMusicUltimate/assets/96953964/e3d4a31b-963a-4d52-bfc9-20ceecf09335)

Linux Ubuntu Ubuntu 22.04.3 with 14.5sdk

I cloned with git

**Comment by dayanch96** [comment]
guess your theos requires using { and }

try this code:
`static NSString *accessGroupID() {
    NSDictionary *query = [NSDictionary dictionaryWithObjectsAndKeys:
                           (__bridge NSString *)kSecClassGenericPassword, (__bridge NSString *)kSecClass,
                           @"bundleSeedID", kSecAttrAccount,
                           @"", kSecAttrService,
                           (id)kCFBooleanTrue, kSecReturnAttributes,
                           nil];
    CFDictionaryRef result = nil;
    OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)query, (CFTypeRef *)&result);
    if (status == errSecItemNotFound) {
        status = SecItemAdd((__bridge CFDictionaryRef)query, (CFTypeRef *)&result);
        if (status != errSecSuccess) {
            return nil;
        }
    }

    NSString *accessGroup = [(__bridge NSDictionary *)result objectForKey:(__bridge NSString *)kSecAttrAccessGroup];

    return accessGroup;
}`

**Comment by binnichtaktiv** [comment]
> guess your theos requires using { and }
> 
> try this code:
> 
> ```
>     if (status == errSecItemNotFound) {
>         status = SecItemAdd((__bridge CFDictionaryRef)query, (CFTypeRef *)&result);
>         if (status != errSecSuccess) {
>             return nil;
>         }
>     }
> ```

Thanks i did that but now I get this 😅
![image](https://github.com/ginsudev/YTMusicUltimate/assets/96953964/fdfb233d-7a6b-4243-ac9e-c49753a751fe)

too old sdk?

**Comment by dayanch96** [comment]
Somethings on your side
