### ISSUE TITLE
Downloaded music requires payment to play [Latest Release]

### ISSUE THREAD

**Issue by KieranBLK** [ginsudev/YTMusicUltimate#171]
[Downloaded music is only a visual change, you still need to pay to play anything that's downloaded, this is likely a serverside check, I doubt this is by-passable with the forced premium option, this will likely require a custom download system that grabs the file directly and saves it in its own container on the device.]

https://github.com/ginsudev/YTMusicUltimate/assets/120525685/fe644d5d-8004-4676-bf86-d40d620d5ecc

**Comment by dayanch96** [comment]
Custom downloading feature implemented in 2.0. Don’t use in-app download button. Play music and long tap on artwork

**Comment by KieranBLK** [comment]
> Custom downloading feature implemented in 2.0. Don’t use in-app download button. Play music and long tap on artwork

Ah I see. That should've have been mentioned in the changelog. Also, the change for the tweaks settings applying live doesn't work, might as well just mention it here since I can't make a new issue for some reason.

**Comment by dayanch96** [comment]
What do you mean by applying live doesn't work?

**Comment by KieranBLK** [comment]
> What do you mean by applying live doesn't work?

"Rewrited settings, most of options applies immediately"

^This does not work. You still have to restart the app in order for any change to the tweaks settings to apply.

**Comment by dayanch96** [comment]
no it works. but obviously not with tab bar or theme settings
