### ISSUE TITLE
Certain features not working

### ISSUE THREAD

**Issue by MrTeed** [ginsudev/YTMusicUltimate#172]
On the newest IPA I have to disable "Force enable premium" for features to work and no matter what I do I cannot use any button on the player except play/pause. If I enable "Force enable premium" I cannot skip more than 6 songs. Any ideas?
Note - no jailbreak version works for me unless I'm on youtube music version 4.19.1 or lower.

**Comment by dayanch96** [comment]
Tried using Canada VPN server and seems like it works on 4.27.53. Are you sore that its 4.19.1 and lower?

**Comment by MrTeed** [comment]
I tried using 4.27.53 as per the other guy that had the same issue a few weeks ago and did not work. The only way I can get it to function 100% is 4.19.1. 
I can get the most current version working fully except I have no shuffle forward or back. I can select any song, no ads, download. 
I’ll probably just have to continue using 14.9.1.

**Comment by Blockr22** [comment]
@MrTeed i have tried changing version number to 4.19.1 but still don’t have unlimited skips & some other features. What else can i do to make it work ? I am in canada, it works if connected to US vpn

**Comment by MrTeed** [comment]
> @MrTeed i have tried changing version number to 4.19.1 but still don’t have unlimited skips & some other features. What else can i do to make it work ? I am in canada, it works if connected to US vpn

I have 2 devices (iPhones) that function all features on 4.19.1 but would prefer a newer version. They work with the current IPA if I use sideloadly and change version. They also both work with newest deb in jailbreak but again only on 14.9.1. My iPad works with newest IPA or newest deb on newest version. I've even tried full wiping both iPhones and still same thing. Thought I couldn't be the only one with this issue and someone might've figured out a fix.

**Comment by Blockr22** [comment]
@MrTeed r u in the US or canada ?

**Comment by MrTeed** [comment]
> @MrTeed r u in the US or canada ?

I am in Canada. I haven't tried any VPN fixes because it's not something I would do every time I want to use it. Weirdly I was able to get everything working on the newest version except shuffle, repeat, skip or back. Download, background playback, no ads, select any song.

**Comment by Blockr22** [comment]
@MrTeed do u have unlimited skips ?

**Comment by MrTeed** [comment]
> @MrTeed do u have unlimited skips ?

I have unlimited skips yes on the 14.9.1 version. If I use the newest I can select any song I want as many times as I want but I can't physically push next song.

**Comment by MrTeed** [comment]
I am chalking this up 100% to a device issue even though I have completely started fresh twice. Both phones I cannot get working but my iPad is working 100% with the newest app and newest deb. Every feature.

**Comment by dayanch96** [comment]
Sign in using another account for some time and and dont turn off force premium option. if you change it too much it will broke features at all

**Comment by MrTeed** [comment]
> Sign in using another account for some time and and dont turn off force premium option. if you change it too much it will broke features at all

I have it working just not on the newest version. Just going to stay where I'm at and be done.

**Comment by Blockr22** [comment]
Latest update is now working for me after force enable premium. All features r working, great timing. Just getting frustrated from Spotify forced shuffle even in Sideloaded app
