### ISSUE TITLE
Not handling special characters in downloads

### ISSUE THREAD

**Issue by mynametoad** [ginsudev/YTMusicUltimate#175]
Steps to repro

1. Search for "AC/DC"
2. Select any song by them
3. Long press on album art
4. Select download
5. Observe UI shows download and it completes
6. Go to downloads
7. Observe no AC/DC songs in downloaded list

Expected result: Able to download and access MP3s with "/" in title. Note other special characters can probably cause this issue as well but I only confirmed forward slash

**Comment by dayanch96** [comment]
Done. Thanks

**Comment by mynametoad** [comment]
Thanks! Will checkout fix in next release.
