### ISSUE TITLE
YTMusicUltimate UIKIT Error when using actions

### ISSUE THREAD

**Issue by arichorn** [ginsudev/YTMusicUltimate#18]
https://github.com/arichorn/YTMusicUltimate/runs/8240011802?check_suite_focus=true
![7E9113C0-D486-4AEA-B29E-CA816849F5FB](https://user-images.githubusercontent.com/78001398/189018060-e42feb9c-24ec-4d8d-b9e3-972959590ec3.jpeg)
I talked about this in #9 so I decided to put this issue here.
This happened when I tried using actions to build the ipa and even after I tried testing out the option to revert YouTube’s new white icons

**Comment by ginsudev** [comment]
Probably best to build with Theos and make sure you have the correct SDKS installed, as well as copying all frameworks from one SDK to theos's include folder.
