### ISSUE TITLE
[Feature Request] Clear cache button

### ISSUE THREAD

**Issue by ttyman0109a** [ginsudev/YTMusicUltimate#181]
I am wondering if you could add a clear cache button.  It helps those of us using ios 17 from having to repeatedly re-installing the app due to application data size

**Comment by dayanch96** [comment]
sure

**Comment by ttyman0109a** [comment]
Thank you very much

**Comment by dayanch96** [comment]
Done: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v2.0.1
