### ISSUE TITLE
Unable to Sign in

### ISSUE THREAD

**Issue by Yofuness** [ginsudev/YTMusicUltimate#19]
Tweak version: 1.19
iOS version: 14.7.1
iPhone model: iPhone 6s
Jailbreak: Odysseyra1n

Tweak version: 1.19
iOS version: 14.4
iPhone model: iPhone 11
Jailbreak: unc0ver with fugu14 untether

In both these scenarios, I just get a sign in error on the latest YouTube music version, 5.23.1. Versions 5.20 and below launch, but youtube premium features don't work, like playing songs instead of radio. When I downloaded the IPA to install via filza, the app crashed.
I will be happy to attach logs or get any other information if possible, I just don't know where the logs are.

Thank you for your amazing work in this tweak!

**Comment by ginsudev** [comment]
> Tweak version: 1.19
> 
> iOS version: 14.7.1
> 
> iPhone model: iPhone 6s
> 
> Jailbreak: Odysseyra1n
> 
> 
> 
> Tweak version: 1.19
> 
> iOS version: 14.4
> 
> iPhone model: iPhone 11
> 
> Jailbreak: unc0ver with fugu14 untether
> 
> 
> 
> In both these scenarios, I just get a sign in error on the latest YouTube music version, 5.23.1. Versions 5.20 and below launch, but youtube premium features don't work, like playing songs instead of radio. When I downloaded the IPA to install via filza, the app crashed.
> 
> I will be happy to attach logs or get any other information if possible, I just don't know where the logs are.
> 
> 
> 
> Thank you for your amazing work in this tweak!

Try re-enabling YTMusicUltimate in the settings if you're using 5.20 or lower. I'll also look into the sign in error shortly :)

**Comment by ginsudev** [comment]
Fixed in v1.1.11
