### ISSUE TITLE
"you can't sign into this app because google can't confirm it's safe" 

### ISSUE THREAD

**Issue by AckeSkriptica** [ginsudev/YTMusicUltimate#190]
I can't sign in app because when I enter my email I get this error "you can't sign into this app because google can't confirm it's safe"
![image](https://github.com/ginsudev/YTMusicUltimate/assets/61045829/181f5ec5-671e-465e-96d3-5d3798d8a991)

**Comment by AckeSkriptica** [comment]
Note: I fixed it by creating new google account, then from in app I clicked add other account, then I tried to add my existing email few times and it worked. It didn't work first time so I'm not sure why it started working after

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/issues/115
