### ISSUE TITLE
Carplay problem 

### ISSUE THREAD

**Issue by S3rialthrilla** [ginsudev/YTMusicUltimate#194]
On my IPhone 13 mini on ios 16.3 using trollstore 2 the app appears in carplay, it opens but I'm not able to find no Playlist, no music...it's just blank tabs

**Comment by dayanch96** [comment]
I highly doubt that carplay is supported

**Comment by S3rialthrilla** [comment]
Using trollstore store should work if the app isn't stripped of entitlements

**Comment by dayanch96** [comment]
I am downloading app on 14.8. Have you tried installing clear YT Music app without any tweak injected via TS2? If it works problem might be in my decrypted ipa

**Comment by S3rialthrilla** [comment]
Ok...I can assist you if maybe you want to take a look 
Anyway, thanks for this great app ;)
