### ISSUE TITLE
Save to playlist bug and other player suggestions

### ISSUE THREAD

**Issue by Saud-97** [ginsudev/YTMusicUltimate#200]
When I try to add a song to my playlists the button doesn't work.
I can add the song to library but even from there when I click options and click save to playlist it doesn't do anything.
This used to work before but not anymore on latest version 2.0.1.

**I really hope if you can add 2 new buttons to players and we can show/hide them. Button to **save to playlist** and another button to start radio.**

I also noticed the bottom "Up next" bar sometimes get bugged and empty.

![image](https://github.com/ginsudev/YTMusicUltimate/assets/39028181/63badbbb-47ed-4758-b1bb-a4491ba98312)

**Comment by dayanch96** [comment]
turn off force premium
