### ISSUE TITLE
Keeps on playing music video when I have the default playback mode to the music sign

### ISSUE THREAD

**Issue by Robbiecookie** [ginsudev/YTMusicUltimate#202]
I’ve restarted my app multiple times to get the song version to play rather than the music video but it just never works. A fix would be appreciated

**Comment by dayanch96** [comment]
No need to duplicate the same issues, read already closed. Thanks

**Comment by Robbiecookie** [comment]
I still don’t have a fixed I commented on the other one but got no replie
