### ISSUE TITLE
The sponsor block doesn’t work

### ISSUE THREAD

**Issue by JackPlaysGames0510** [ginsudev/YTMusicUltimate#213]

**Comment by Ketarmin** [comment]
@JackPlaysGames0510 hey you opened a issu in a Twitter Repo where you asked how to change an icon 

https://github.com/ghl3m0n/FuckElon/issues/2#issuecomment-2254172514

I want to asked you if you can help me with something similar.
I want to change the app icon from X to the old bird but it doesn’t work for me 

Do you know what I have to do ?

![Image](https://github.com/user-attachments/assets/ec358f54-3f52-421b-a18e-8dcf1b7505c1)


Sorry sorry @dayanch96 to use this for a question which have nothing to do with your tweak at all but I haven’t found a way to contact him.

Maybe you can help me 


Again apologize a lot for this

**Comment by JackPlaysGames0510** [comment]
if you want to talk to me message me on telegram @Jacks_Apps0510 and turn off fix icon
