### ISSUE TITLE
problem building project (typo in the path name)

### ISSUE THREAD

**Issue by ttyman0109a** [ginsudev/YTMusicUltimate#215]
It seems that there is a problem when I try to build the project: (It seems that there is a typo in the path name: "Userss")

➜  YTMusicUltimate git:(main) make clean package sideloading=1
==> Cleaning…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for tweak YTMusicUltimate…
==> Compiling Source/Prefs/NavBarSettingsController.m (arm64)…
<built-in>:1:10: error: non-portable path to file '"Userss/my user name/theos/Prefix.pch"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#include "/users/my user name/theos/Prefix.pch"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "Userss/my user name/theos/Prefix.pch"
1 error generated.
make[3]: *** [/Users/<my user name>/documents/documents/ytmu/YTMusicUltimate/.theos/obj/debug/arm64/Source/Prefs/NavBarSettingsController.m.f89a7572.o] Error 1
make[2]: *** [/Users/<my user name>/documents/documents/ytmu/YTMusicUltimate/.theos/obj/debug/arm64/YTMusicUltimate.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [YTMusicUltimate.all.tweak.variables] Error 2

**Comment by dayanch96** [comment]
It's not tweak-related issue

**Comment by ttyman0109a** [comment]
Do you have any idea what the problem maybe?
