### ISSUE TITLE
IPAs app releases

### ISSUE THREAD

**Issue by Saud-97** [ginsudev/YTMusicUltimate#216]
First of all I'm really thankful for all the hard work put into this project.
I noticed lately all IPAs were removed from releases and the latest version didn't include an IPA. 

Can you please consider making them again as I use them to sideload. Maybe leave them at an other user/repo / external source that is only for releases so it be more isolated and can be discarded any time.

**Comment by dayanch96** [comment]
Due to a recently received DMCA we will no longer be posting IPAs
