### ISSUE TITLE
Repo is out of date

### ISSUE THREAD

**Issue by GainingAccess** [ginsudev/YTMusicUltimate#217]
Still uses v1.5.2, instead of v2.0.2
![IMG_3699](https://github.com/ginsudev/YTMusicUltimate/assets/110878258/37bb3a71-e0e4-4d65-8fee-52ca07bc3318)

**Comment by dayanch96** [comment]
Has nothing to do with Github repo. Latest version available in releases. You can contact Ginsu via discord channel
