### ISSUE TITLE
Version of YouTube Music that work with tweak

### ISSUE THREAD

**Issue by ttyman0109a** [ginsudev/YTMusicUltimate#218]
I patched a decrypted youtube music 6.42 with the tweak, signed it.  But it doesn't install properly.  Gets the cloud/download symbol next to the app name.

Does the tweak work with this version or do I need another version

**Comment by dayanch96** [comment]
Sorry, but what do your skills in injecting a tweak into an ipa have to do with the tweak itself?

**Comment by ttyman0109a** [comment]
It doesn't.. maybe I got the wrong IPA?  

The command line that I used:
azule -n YTUltimate-2.0.2_6.42 -i /Users/myUserName/Downloads/com.google.ios.youtubemusic_6.42_und3fined.ipa -o ~/desktop/ -f /Users/myUserName/Downloads/com.ginsu.ytmusicultimate_2.0.2_iphoneos-arm.deb

**Comment by dayanch96** [comment]
I cant tell that. Please refrain from creating issues that are not directly related to the tweak itself. Thank you❤

**Comment by mustafacakirogludev** [comment]
@ttyman0109a try changing the bundle id and the name of the app, it will work like that. this is a workaround but should do the job.

**Comment by dayanch96** [comment]
Reopening since it looks like actions issue, have to take a look at it later anyway

**Comment by ttyman0109a** [comment]
> @ttyman0109a rename the ipa file and change the extension to .zip. Open the zip file and go Payload->YoutubeMusic.app. There will be a folder called "Watch", delete that folder. Go back and rename the .zip to .ipa and sideload it. It'll work.

Hmm... That doesn't seem to work.

**Comment by mustafacakirogludev** [comment]
> Hmm... That doesn't seem to work.

You can also try changing the app name and the bundle id while sideloading the ipa. If this also does not work, you'll have to wait for my pull request to be merged to use Github Actions. Like dayanch96 said, this is not directly related with the tweak so that's all I can do for you at the moment.

**Comment by ttyman0109a** [comment]
It worked.  I forgot to sign it.  My bad.  Thank you for your help.

**Comment by dayanch96** [comment]
Closing since it completed here: https://github.com/mustafacakirogludev/YTMusicUltimate
