### ISSUE TITLE
doesn't work with trollstore (cannot sign in)

### ISSUE THREAD

**Issue by mailinglists35** [ginsudev/YTMusicUltimate#22]
it works with sideloadly

using trollstore I am offered the sign-in screen then after typing in my email account I am getting a message from google.

using AppStore the app offers me to login using already found account on device

![image](https://user-images.githubusercontent.com/2054302/191264344-55100b65-a574-485b-99cc-16f505f84d11.jpeg)

![image](https://user-images.githubusercontent.com/2054302/191264398-9d2858a5-a3ee-47be-a393-497069594161.jpeg)

![image](https://user-images.githubusercontent.com/2054302/191264418-65e03cab-697a-4477-a2aa-16e593048273.png)

**Comment by mailinglists35** [comment]
could you maybe talk to https://github.com/opa334/TrollStore and/or

**Comment by mailinglists35** [comment]
nope, it doesn't work in sideloadly either! it used to work ok in sideloadly

**Comment by mailinglists35** [comment]
alright, it seems to be a trollstore issue.

deleted the app and reinstalled with sideloadly = signs in
deleted the app and reinstalled with trollstore = doesn't sign in.

**Comment by mailinglists35** [comment]
trollstore issue if anyone else affected https://github.com/opa334/TrollStore/issues/96

**Comment by mailinglists35** [comment]
opa334 says it's the issue with the IPA, and not Trollstore.

https://github.com/opa334/TrollStore/issues/96#issuecomment-1252512273

**Comment by mailinglists35** [comment]
@ginsudev could you please get in touch with @opa334 to clarify what is the root cause?

**Comment by ginsudev** [comment]
It's not an issue with TrollStore, it's just that Google is detecting that the app is side loaded. I have fixed the issue tho and will be posting a new version soon.

**Comment by mailinglists35** [comment]
>it's just that Google is detecting that the app is side loaded


oh, interesting. I'm wondering though how can they detect that under Trollstore but not via Sideloadly.

anyway, can't wait for the updated version, many thanks for your continued work! :-)

**Comment by mailinglists35** [comment]
yey, works, thank you!

it doesn't recognizes the saved google accounts on device, though - I assume this is caused by putting the sideloaded app into a different shared app group, correct?

cheers!
