### ISSUE TITLE
no able to understand 

### ISSUE THREAD

**Issue by bijay085** [ginsudev/YTMusicUltimate#221]
I am not able to understand the introduction , sorry but can u please explain step by step i am new to this step

**Comment by dayanch96** [comment]
What are you trying to understand?

**Comment by bijay085** [comment]
how to inject .deb file into ytmusic ipa

**Comment by dayanch96** [comment]
take a look at this fork:

https://github.com/mustafacakirogludev/YTMusicUltimate

**Comment by bijay085** [comment]
build and release workflow failed for main branch

**Comment by dayanch96** [comment]
create new issue there. not here

**Comment by bijay085** [comment]
where to create issue ?
