### ISSUE TITLE
listen dont delete

### ISSUE THREAD

**Issue by bijay085** [ginsudev/YTMusicUltimate#224]
![image](https://github.com/ginsudev/YTMusicUltimate/assets/107698781/7914d0ff-db3c-4d02-becf-6d984adcee6b)

i run the workflow , ipa is extracted by me and uploaded in dropbox 
it is completed but nothing is showing in "build and release" section

please dont dont delete

**Comment by dayanch96** [comment]
check your releases

**Comment by mustafacakirogludev** [comment]
You are trying extra hard to get banned my friend. THE ACTION YOU ARE USING IS NOT FROM THIS REPO. You are basically going to Domino's and complaining about the pizza you bought from Pizza Hut.

**Comment by bijay085** [comment]
![image](https://github.com/ginsudev/YTMusicUltimate/assets/107698781/f15d223a-3a48-4b93-9a42-f6fe352c8b4a)

where ? there is no option

**Comment by bijay085** [comment]
sorry sir , but i a, very bad at reading instruction

**Comment by bijay085** [comment]
there is no option of build and release

**Comment by dayanch96** [comment]
https://github.com/bijay085/YTMusicUltimate/releases

**Comment by bijay085** [comment]
sorry i am dumb 
u can close now
