### ISSUE TITLE
is:issue is:open Hi, No IPA showing up on updates, how can i get the latest IPA? Thanks

### ISSUE THREAD

**Issue by ginodurazo** [ginsudev/YTMusicUltimate#227]
Hi, wondering why doesn't shows the latest IPA for download? Thank You

**Comment by dayanch96** [comment]
No more IPA’s in releases

**Comment by ginodurazo** [comment]
Thank you Dan, and please excuse me if i posted in a wrong place. May i ask if or where is going to be IPA? Many thanks in advance. GinoEl 16 mar 2024, a la(s) 3:35 p.m., Dan ***@***.***> escribió:﻿
No more IPA’s in releases
