### ISSUE TITLE
No ipa file?

### ISSUE THREAD

**Issue by antoripdas** [ginsudev/YTMusicUltimate#229]
I only see the .deb file, how to download the ipa file?

**Comment by mustafacakirogludev** [comment]
Next time, look for similar issues before creating a new one. 

tl;dr google does not allow us to share IPA files anymore. You need to build your own using github actions:

[How to build your own IPA file.](https://github.com/ginsudev/YTMusicUltimate?tab=readme-ov-file#how-to-build-a-ytmusicultimate-ipa-by-yourself-using-github-actions)
