### ISSUE TITLE
The last ipa is 1.1.13v not 1.1.14v

### ISSUE THREAD

**Issue by m5099m** [ginsudev/YTMusicUltimate#26]
Can you please upload the new version? The ipa that write 1.1.14 its 1.1.13
And please 🙏🏽 can you make that the CarPlay will think it’s a premium account?
![F6D3732E-BBEA-4BF8-B2C2-55A0697759FE](https://user-images.githubusercontent.com/114489192/192519977-d2aced21-e61d-4c5a-be78-cf88ca7cf921.png)

**Comment by ginsudev** [comment]
Actually it is v1.1.14. I just forgot to change the text inside the tweak.

**Comment by m5099m** [comment]
Can you please 🙏🏽 make that the CarPlay will think it’s a premium account?
