### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Clayton630** [ginsudev/YTMusicUltimate#33]
The Google sign in issue isn’t fixed, I’m still unable to log in

**Comment by qnblackcat** [comment]
@ginsudev we only need the fix-login (2). Keeping the fix-login (1) will break the fix-login (2). We can just remove the fix-login (1) code

**Comment by Clayton630** [comment]
Ok, where can I find it in the ipa file ?

**Comment by Mordecai20010** [comment]
> Ok, where can I find it in the ipa file ?

Did you try opening the app directly from the TrollStore or altstore if you can. Because it just loaded the app after that

**Comment by Clayton630** [comment]
Yes, of course the app is loading but once installed, I can’t sign in. Qnblackcat said I needed to remove the fix-login 1 in order to keep the fix login 2 only. So, I decrypted the ipa to find it but I don’t know where this fix is located cause there are so many files, and that was my question

**Comment by ginsudev** [comment]
I'm posting an updated version in a few minutes, maybe try that.

**Comment by Clayton630** [comment]
Ok thanks

**Comment by ginsudev** [comment]
> Ok thanks

Try the new iPA I just posted

**Comment by Clayton630** [comment]
Perfect ! It works !
