### ISSUE TITLE
[Feature Request] Audio only mode

### ISSUE THREAD

**Issue by Clayton630** [ginsudev/YTMusicUltimate#34]
Hello, I just come to request a feature, being able to toggle on « Don’t play music videos », a feature that is exclusive to premium subscribers for now. This is a simple feature that makes YouTube Music play songs without showing the video clip by default

**Comment by Willy-JL** [comment]
#21

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/releases
