### ISSUE TITLE
Integrity Issue Solved

### ISSUE THREAD

**Issue by IphoneCake** [ginsudev/YTMusicUltimate#38]
I have an integrity problem 

Version 1.2.5 cannot be installed on IOS 16.0.3.

I have tried to install it several times.

The Iphone says the app has no integrity.

Is there anything I can do to fix this?

Thx for help 

many greetings

**Comment by IphoneCake** [comment]
Nevermind Sideload accepts only three Sideloaded apps. App works perfect.

**Comment by stevansunarno** [comment]
I got the integrity issue. @IphoneCake , how did you solve this error message? Thanks.

**Comment by ginsudev** [comment]
You just need to uninstall one of your other sideloaded apps. You can only have 3 maximum.

**Comment by stevansunarno** [comment]
Thanks for the answer @ginsudev , but I do not have any sideloaded apps in my phone. I use ip8 ios 15.7.

**Comment by dayanch96** [comment]
Try using latest release and feel free to re-open issue if needed.

https://github.com/ginsudev/YTMusicUltimate/releases
