### ISSUE TITLE
Stutter at latest version

### ISSUE THREAD

**Issue by gototheskinny** [ginsudev/YTMusicUltimate#51]
stutters while playing vid. I guess while automatically  resolution changes and sometimes randomly. But it's annoying for sure.
Device:iphone 12 w/ios 15.0 and TrollStore

**Comment by dayanch96** [comment]
Kanka, i'm not sure if there any problem with tweak itself

**Comment by gototheskinny** [comment]
> Kanka, i'm not sure if there any problem with tweak itself. Cant even reproduce it.

Hocam, I haven't used this tweak since than. You can close this if you don't have any issues.

**Comment by dayanch96** [comment]
Tamam. Sana zahmet, müsait vaktinde türk diline de bi göz atar mısın. Bazı kelimeleri doğru çevirip çevirmediğimden emin değilim. Uzun zamandır uğlumaları ingiliz veya rus dilinde kullanıyorum.

**Comment by gototheskinny** [comment]
> Tamam. Sana zahmet, müsait vaktinde türk diline de bi göz atar mısın. Bazı kelimeleri doğru çevirip çevirmediğimden emin değilim. Uzun zamandır uğlumaları ingiliz veya rus dilinde kullanıyorum.

Türkçe'de bir sorun göremedim. Yeterli.

**Comment by dayanch96** [comment]
Eyw
