### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by IWentPro** [ginsudev/YTMusicUltimate#52]
Getting an error from google "You can't sign in to this app because Google can't confirm that it's safe."

**Comment by alexxvii-git** [comment]
I was having this issue as well. It's a move by Google to try to block modified YouTube apps.

The solution is simple, we will need uYou+ to resolve it.

First, Download the latest uYou+ IPA to your device as well as the YouTubeMusic Ultimate IPA
Make sure you save both to a location you can access.

We then follow [THIS](https://github.com/qnblackcat/uYouPlus/discussions/447#discussion-4380947) updated guide.
(Make sure to sign into uYou+ with the email you'd like to use for YouTube Music Ultimate.

Once the guide is complete, remove uYou+ and sideload the Youtube Music Ultimate IPA.
If done correctly, YouTubeMusic Ultimate will automatically sign you into the email and will bypass any of Google's restrictions.

Enjoy

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/issues/62
