### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by iParix** [ginsudev/YTMusicUltimate#56]
"you can't sign into this app because google can't confirm it's safe"

**Comment by shakedhaiim** [comment]
Happening to me also :( is there any way to solve it?

**Comment by arichorn** [comment]
https://github.com/qnblackcat/uYouPlus/discussions/447#discussion-4380947
try this, even if it’s from a different app it should work

**Comment by patkozlowski** [comment]
Can confirm that @arichorn suggestion works for both this project as well as the uyou plus app.

**Comment by alexxvii-git** [comment]
> "you can't sign into this app because google can't confirm it's safe"

I was having this issue as well. It's a move by Google to try to block modified YouTube apps.

The solution is simple, we will need uYou+ to resolve it.

First, Download the latest uYou+ IPA to your device as well as the YouTubeMusic Ultimate IPA
Make sure you save both to a location you can access.

We then follow [THIS](https://github.com/qnblackcat/uYouPlus/discussions/447#discussion-4380947) updated guide.
(Make sure to sign into uYou+ with the email you'd like to use for YouTube Music Ultimate.

Once the guide is complete, remove uYou+ and sideload the Youtube Music Ultimate IPA.
If done correctly, YouTubeMusic Ultimate will automatically sign you into the email and will bypass any of Google's restrictions.

Enjoy

**Comment by dayanch96** [comment]
Fixed: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.3.2
