### ISSUE TITLE
Can not Login v1.2.7 Install with AltStore and Developer Account

### ISSUE THREAD

**Issue by Titanius** [ginsudev/YTMusicUltimate#57]
I can not Login "you can't sign into this app because google can't confirm it's safe"
I Install with AltStore and Developer Account. iOS 16
Do i have to Edit the Capabilities in "your App ID Configuration" in my Developer Account?

**Comment by alexxvii-git** [comment]
I was having this issue as well. It's a move by Google to try to block modified YouTube apps.

The solution is simple, we will need uYou+ to resolve it.

First, Download the latest uYou+ IPA to your device as well as the YouTubeMusic Ultimate IPA
Make sure you save both to a location you can access.

We then follow [THIS](https://github.com/qnblackcat/uYouPlus/discussions/447#discussion-4380947) updated guide.
(Make sure to sign into uYou+ with the email you'd like to use for YouTube Music Ultimate.

Once the guide is complete, remove uYou+ and sideload the Youtube Music Ultimate IPA.
If done correctly, YouTubeMusic Ultimate will automatically sign you into the email and will bypass any of Google's restrictions.

Enjoy

**Comment by carlni2008** [comment]
Your method didn't work ;(

**Comment by dayanch96** [comment]
https://github.com/ginsudev/YTMusicUltimate/issues/62

**Comment by dayanch96** [comment]
@Titanius @carlni2008 here you go: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.3.2
