### ISSUE TITLE
Application binary is broken unable to sign

### ISSUE THREAD

**Issue by MoSala7** [ginsudev/YTMusicUltimate#6]
Signing error: unable to sign, Application binary is broken unable to sign, Application binary is broken

i receive this error when installing the ipa using appdb, they told me that the application is not valid, any solution please!

**Comment by ginsudev** [comment]
No idea, that iPA is unofficial. You can find an official iPA in the releases section of this repo.

**Comment by MoSala7** [comment]
> No idea, that iPA is unofficial. You can find an official iPA in the releases section of this repo.

Yes, i've tried v1.1.5 and v1.1.2 from the releases section of this repo and both with the same error
<img width="619" alt="Screenshot_2" src="https://user-images.githubusercontent.com/32467495/182147831-edd891af-058b-4d07-aaea-38d77adebfc6.png">
oth with same error

**Comment by MoSala7** [comment]
Solved:
installed using sideloadly application, and it works fine :)
