### ISSUE TITLE
Suggestion: Installation through test flight

### ISSUE THREAD

**Issue by BitMap4** [ginsudev/YTMusicUltimate#64]
Is it possible to allow installation through test flight as a beta tester, like how [Aidoku/Aidoku](https://github.com/Aidoku/Aidoku) does it? Honestly, it is much simpler and faster than with altstore.

**Comment by MasterBladeX** [comment]
Already a thing through discord. Test flight slots are almost always filled though but sometimes do open up.

**Comment by bachig26** [comment]
> Already a thing through discord. Test flight slots are almost always filled though (only 10k slots) but sometimes do open up.

Can you share me the server invite?

**Comment by dayanch96** [comment]
Its not recommended/possible since its a clear hack on the yt music app
