### ISSUE TITLE
YTMusicUltimate 1.1.5 updated and fixed ipa (YTMusic v5.18) [Download Link]

### ISSUE THREAD

**Issue by arichorn** [ginsudev/YTMusicUltimate#7]
# Since the developer hasn’t updated or fixed the YouTube Music IPA, I decided to do it!
**changes:**
- Updated YouTube Music ipa to version 5.18
- This ipa shouldn’t cause errors whenever sideloading the app on Altstore hopefully. #1 
- Black screen error shouldn’t happen no more unless it wasn’t because of the ipa. #5 
**August 9th 2022 - Edited the topic to fix spelling mistakes or missing words**
# [YTMusicUltimate 1.1.5 - v5.18 IPA](https://www.mediafire.com/file/ffgojkpcg514lw7/YTMusicUltimate_5.18.ipa/file)

**Comment by iammanpreetsingh** [comment]
> # Since the developer hasn’t updated or fixed YouTube Music Ultimate, I decided to do it!
> **changes:**
> 
> * Updated YouTube Music ipa to version 5.18
> * This ipa shouldn’t cause errors using the sideloading app on Altstore now. [crash when locking screen #1](https://github.com/ginsudev/YTMusicUltimate/issues/1)
> * Black screen error shouldn’t happen no more. [Black screen #5](https://github.com/ginsudev/YTMusicUltimate/issues/5)
> 
> # [YTMusicUltimate 1.1.5.1](https://www.mediafire.com/file/ffgojkpcg514lw7/YTMusicUltimate_5.18.ipa/file)

How did you fixed "crashes" and black screen"?

**Comment by ginsudev** [comment]
> # Since the developer hasn’t updated or fixed YouTube Music Ultimate, I decided to do it!
> 
> **changes:**
> 
> - Updated YouTube Music ipa to version 5.18
> 
> - This ipa shouldn’t cause errors using the sideloading app on Altstore now. #1 
> 
> - Black screen error shouldn’t happen no more. #5 
> 
> 
> 
> # [YTMusicUltimate 1.1.5.1](https://www.mediafire.com/file/ffgojkpcg514lw7/YTMusicUltimate_5.18.ipa/file)

Thanks, would you mind submitting a pull request? I didn't have time to fix it because of university.

**Comment by iammanpreetsingh** [comment]
> > # Since the developer hasn’t updated or fixed YouTube Music Ultimate, I decided to do it!
> > **changes:**
> > 
> > * Updated YouTube Music ipa to version 5.18
> > * This ipa shouldn’t cause errors using the sideloading app on Altstore now. [crash when locking screen #1](https://github.com/ginsudev/YTMusicUltimate/issues/1)
> > * Black screen error shouldn’t happen no more. [Black screen #5](https://github.com/ginsudev/YTMusicUltimate/issues/5)
> > 
> > # [YTMusicUltimate 1.1.5.1](https://www.mediafire.com/file/ffgojkpcg514lw7/YTMusicUltimate_5.18.ipa/file)
> 
> Thanks, would you mind submitting a pull request? I didn't have time to fix it because of university.

It's not fixed, still crashing. I am testing the my users are testing the IPA though

**Comment by arichorn** [comment]
It doesn’t actually fixed the problems, I’m just saying that because of the ipa of YouTube Music, the original ipa in releases has errors when sideloading so I used an ipa that shouldn’t break this. And also cannot do a pull request since nothing has changed apart from downloading the tweak.

**Comment by arichorn** [comment]
> > # Since the developer hasn’t updated or fixed YouTube Music Ultimate, I decided to do it!
> > **changes:**
> > 
> > * Updated YouTube Music ipa to version 5.18
> > * This ipa shouldn’t cause errors using the sideloading app on Altstore now. [crash when locking screen #1](https://github.com/ginsudev/YTMusicUltimate/issues/1)
> > * Black screen error shouldn’t happen no more. [Black screen #5](https://github.com/ginsudev/YTMusicUltimate/issues/5)
> > 
> > # [YTMusicUltimate 1.1.5.1](https://www.mediafire.com/file/ffgojkpcg514lw7/YTMusicUltimate_5.18.ipa/file)
> 
> Thanks, would you mind submitting a pull request? I didn't have time to fix it because of university.

The problems weren’t actually solved, I was referring to the ipa since I’ve seen amount of problems when I tried sideloading it. This version uses a more stable decrypted ipa and might fix the could or could not fix issues with it

**Comment by ginsudev** [comment]
Alright, I'm working on fixing the issues myself rn.

**Comment by arichorn** [comment]
ginsudev sorry. I was giving users this ipa since fixes some sideloading errors that the original release had.
If I could fix the issues then I have to make them crash the app and get the crash log of the issues.

**Comment by ginsudev** [comment]
All good haha. I've just fixed the issues actually, I'll be posting an update soon after some testing

**Comment by arichorn** [comment]
Also ginsudev I recommend using this to get ipas just because these are more decrypted and reliable to use. https://armconverter.com/decryptedappstore/YouTube%20Music
Whenever I use your ipa in releases then you’ll get errors whenever you try to sideload the app on the altstore or some other sideloading apps, and YouTube Music just updated a few minutes ago on there if you needed to know.

**Comment by patkozlowski** [comment]
Thanks for the continued work on this.  I think addressing the stability of the app (crashing in background) will make this great, and can't wait for it.  I hope the updates fix this issue.  I know you will get there!

**Comment by arichorn** [comment]
1.1.6 is already out, I gave the developer the url to the best decrypted ipas which will greatly improve sideloading problems with the sideloading programs we use
