### ISSUE TITLE
Crash on launch on iPad Air 3 14.7

### ISSUE THREAD

**Issue by ikadatym-sry** [ginsudev/YTMusicUltimate#80]
I cannot upload crash log file via GitHub somehow, so I uploaded by gg drive instead
Here is the log file. Hope it help you to fix this crash bug!
https://drive.google.com/file/d/1sFiQsYpAi9hre0yZDcHWLBdLwjfAZE-P/view?usp=drivesdk

**Comment by dayanch96** [comment]
Hey. Can you test latest release?

**Comment by dayanch96** [comment]
Give me a minute, going to build ipa with missing on ios 14 lib

**Comment by dayanch96** [comment]
Welp, can you provide more info? Like installation method and type

**Comment by ikadatym-sry** [comment]
Using Trollstore and it not crash on version 1.2.7

**Comment by dayanch96** [comment]
> Using Trollstore and it not crash on version 1.2.7

Whats crash log says on last ipa? Still cant find libswift_Concurrency.dylib?

**Comment by ikadatym-sry** [comment]
Yes still cant find it
_____
Termination Description: DYLD, dyld: Using shared cache: 3BF779D6-4A31-311F-A35E-4F5BD5FB3132 | dependent dylib '@rpath/libswift_Concurrency.dylib' not found for '/private/var/containers/Bundle/Application/6BE5FC89-89C5-46A4-A3DF-4B1089E768CB/YouTubeMusic.app/YouTubeMusic'. could not use '/private/var/containers/Bundle/Application/6BE5FC89-89C5-46A4-A3DF-4B1089E768CB/YouTubeMusic.app/Frameworks/libswift_Concurrency.dylib' because it was not built for platform iOS

**Comment by dayanch96** [comment]
> Yes still cant find it

Nope, now it shows different issue. Re-uploaded again. Let me know if it works

**Comment by ikadatym-sry** [comment]
Good news. Now it’s work. 
![B65383F0-8525-4BC1-ABBB-B641E0E8D642](https://user-images.githubusercontent.com/78898421/235032282-83ec4bf2-909c-4f58-9673-3095246b9f6b.jpeg)
