### ISSUE TITLE
can't install latest version

### ISSUE THREAD

**Issue by LukIsHere** [ginsudev/YTMusicUltimate#82]
while installing the latest version altstore gives me an error :

Installed profile: com.google.ios.youtube.RJXM7ANY9Q.OpenYoutube.Extension (cfaa2777-4845-4fa3-9cfe-69ea9d6cb0d0)
Installed profile: com.google.ios.youtube.RJXM7ANY9Q.ShareExtension (fe5c25ce-7dd7-4bb3-b6d8-acbaec65b5b3)
Alert: Could not install YTMusicUltimate.ipa to unknown.
    Invalid value of WKCompanionAppBundleIdentifier key in WatchKit 2.0 app's Info.plist: com.google.ios.youtubemusic (expected com.google.ios.youtubemusic.RJXM7ANY9Q)

**Comment by dayanch96** [comment]
try using Sideloadly

**Comment by LukIsHere** [comment]
so i've deleted Payload/YouTubeMusic.app/com.apple.WatchPlaceholder folder inside ipa file and now it works
