### ISSUE TITLE
YouTubeMusicUltimate v1.3.2 can't install, v1.2.7 works fine 

### ISSUE THREAD

**Issue by IphoneCake** [ginsudev/YTMusicUltimate#83]
Hey,
 
Does anyone have the same problems ? 
Version 1.2.7 works without problems. But when I want to update to version 1.3.2 AltStore won't let me install it. It always comes Youtube Music can not be installed at this time, try at a later time. Tried AltStore installation via WIFI and cable, same problem. 
Have currently installed version 1.2.7 again.

Anyone have a solution ?

Kind regards Dominik

**Comment by dayanch96** [comment]
Try using sideloadly

**Comment by IphoneCake** [comment]
> Try using sideloadly

I will try this tomorrow, but i love altstore because of the refresh ability

**Comment by dayanch96** [comment]
> > Try using sideloadly
> 
> I will try this tomorrow, but i love altstore because of the refresh ability

But don't delete already installed YTMusic otherwise you may have problems with authorization
