### ISSUE TITLE
Google cant verify that this app is safe error

### ISSUE THREAD

**Issue by R3TR3AT** [ginsudev/YTMusicUltimate#84]
I keep getting this error every time I try to install the app through sideloadly and altstore but appdb works fine

**Comment by dayanch96** [comment]
What do you mean by appdb? Free or Paid cert?

**Comment by picosen** [comment]
> What do you mean by appdb? Free or Paid cert?

I got same issue with Free cert. Some developer did counter this problem.

example : uYouPlus+
Idk how they did it but yeah it fixed the login issue on uYouPlus+
Hopefully the dev know how to fix this using the same method with uYouPlus+

**Comment by dayanch96** [comment]
'same method' wont work on yt music

**Comment by picosen** [comment]
> 'same method' wont work on yt music

why not?

**Comment by dayanch96** [comment]
its not youtube

**Comment by dayanch96** [comment]
Fixed in latest release: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.4.0
