### ISSUE TITLE
New features 

### ISSUE THREAD

**Issue by JackPlaysGames0510** [ginsudev/YTMusicUltimate#85]
Can you add an feature to stay on video by default

**Comment by N04-Git** [comment]
Or to stay on audio as well ?😅 It consumes a lot of data in video ... thanks you !

**Comment by dayanch96** [comment]
> Can you add an feature to stay on video by default

Its called YouTube

**Comment by dayanch96** [comment]
> Or to stay on audio as well ?😅 It consumes a lot of data in video ... thanks you !

It is already stay on audio by default

**Comment by N04-Git** [comment]
> > Or to stay on audio as well ?😅 It consumes a lot of data in video ... thanks you !
> 
> 
> 
> It is already stay on audio by default

Hello, You right but on an older version, it was not.

**Comment by dayanch96** [comment]
> > > Or to stay on audio as well ?😅 It consumes a lot of data in video ... thanks you !
> > 
> > 
> > It is already stay on audio by default
> 
> Hello, You right but on an older version, it was not.

👋, Still using old version?

**Comment by JackPlaysGames0510** [comment]
> > Can you add an feature to stay on video by default
> 
> Its called YouTube

Yeah true

**Comment by dayanch96** [comment]
Added in latest release: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.3.4
