### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JackPlaysGames0510** [ginsudev/YTMusicUltimate#87]
This bug happens when you rotate your phone back to vertical and turn it to a MiniPlayer
![IMG_0678](https://user-images.githubusercontent.com/48178959/235833923-450e5a1d-a256-4931-a301-e7b4518a46e2.png)

**Comment by JackPlaysGames0510** [comment]
Look on the top

**Comment by dayanch96** [comment]
its google apps problem
