### ISSUE TITLE
Error installing v1.3.4

### ISSUE THREAD

**Issue by zafie** [ginsudev/YTMusicUltimate#88]
Getting this error from altstore finishing the installation of the ipa.
IOS 16.4.1a
Any clues?

Invalid value of WKCompanionAppBundleIdentifier key in WatchKit 2.0 app's Info.plist: com.google.ios.youtubemusic (expected com.google.ios.youtubemusic.L2AD8FTSPA)

**Comment by dayanch96** [comment]
remove extensions
