### ISSUE TITLE
[Feature Request/Interface Request] Revert the High Contrast UI Tweak

### ISSUE THREAD

**Issue by arichorn** [ginsudev/YTMusicUltimate#9]
Hello ginsudev! I’ve been trying to implement another option for YTMusicUltimate to reduce eye sore but I wasn’t able to get it right and pull request it here but this is also a nice ui addition if you have YTMusicUltimate’s OLED Mode option enable with it. But I am having trouble actually implementing this option to YouTube Music since YTCommonColorPalette isn’t the same just like the Normal YouTube version.
```
%group gYTDisableHighContrastIcons
%hook YTCommonColorPalette
 - (UIColor *)textPrimary {
      if (self.pageStyle == 1) {
          return [UIColor colorWithWhite:0.565 alpha:1];
      }
          return [UIColor colorWithWhite:0.5 alpha:1];
  }
 - (UIColor *)textSecondary {
     if (self.pageStyle == 1) {
         return [UIColor colorWithWhite:0.565 alpha:1];
      }
         return [UIColor colorWithWhite:0.5 alpha:1];
  }
%end
%end
```
This is from the normal YT app but just to let you know that self.pageStyle doesn’t seem to exist in YTMusic. But other then that this is a great tweak if wanting to have an option to customize and revert the color from YouTube’s old UI

Image with the tweak on uYouPlus
![224191A8-DE90-4983-922F-0E530AC9DB1F](https://user-images.githubusercontent.com/78001398/184007660-2bd7f15a-e086-429d-9df6-71726e0b28ba.jpeg)

**Comment by ginsudev** [comment]
Thanks! I'll try to add it soon

**Comment by arichorn** [comment]
Alright! no problem!

**Comment by arichorn** [comment]
Hello! I also realized YouTube Music never had light mode so that’s why pageStyle doesn’t exist in this version of YouTube 
```
%group gYTDisableHighContrastIcons
%hook YTCommonColorPalette
 - (UIColor *)textPrimary {
      if (self.pageStyle == 1) {
          return [UIColor colorWithWhite:0.5 alpha:1];
  }
 - (UIColor *)textSecondary {
     if (self.pageStyle == 1) {
         return [UIColor colorWithWhite:0.5 alpha:1];
  }
%end
%end
```
this version of the code removes the modifed YT Light Theme UIColor
`return [UIColor colorWithWhite:0.565 alpha:1];`
Also I’m still trying to find a different method for pageStyle but right now I got nothing for that at the moment.

**Comment by arichorn** [comment]
And also this too https://github.com/arichorn/YTMusicDisableHighContrastIcons
This hasn’t been updated since I haven’t figured out YTMusic’s method to YTCommonColorPalette

**Comment by arichorn** [comment]
This is so tricky, since light theme doesn’t exist on ytmusic, the method is pretty hard because I don’t have a clue if TextPrimary & TextSecondary will work.

**Comment by ginsudev** [comment]
I can try looking into it soonish (probably after next Wednesday)

**Comment by arichorn** [comment]
Oh alright

**Comment by arichorn** [comment]
and also hold on, I’m gonna try a different method, I went around YTMusicUltimate and found something that might work

**Comment by arichorn** [comment]
@ginsudev heres the new method, I was stupid for not scrolling through YTMusicUlitimate’s Tweak.x File but since I did it, I think this should work.
```
%group gYTMusicDisableHighContrastIcons
%hook YTCommonColorPalette
- (UIColor *)textPrimary { return [UIColor colorWithRed: 0.56 green: 0.56 blue: 0.56 alpha: 1.00]; }
- (UIColor *)textSecondary { return [UIColor colorWithRed: 0.56 green: 0.56 blue: 0.56 alpha: 1.00]; }
%end
%end
```
Also I haven’t confirmed that this method works, I do recommend putting this as a on/off setting if this does work. Not all users will like it but it’s good for your eyes + feels nostalgic.

**Comment by arichorn** [comment]
Also the reason why I’m not testing it is because of an error in your code which doesn’t let me build the ipa

**Comment by ginsudev** [comment]
Which error? Compiles fine for me

**Comment by ginsudev** [comment]
> @ginsudev heres the new method, I was stupid for not scrolling through YTMusicUlitimate’s Tweak.x File but since I did it, I think this should work.
> 
> ```
> 
> %group gYTMusicDisableHighContrastIcons
> 
> %hook YTCommonColorPalette
> 
> - (UIColor *)textPrimary { return [UIColor colorWithRed: 0.56 green: 0.56 blue: 0.56 alpha: 1.00]; }
> 
> - (UIColor *)textSecondary { return [UIColor colorWithRed: 0.56 green: 0.56 blue: 0.56 alpha: 1.00]; }
> 
> %end
> 
> %end
> 
> ```
> 
> Also I haven’t confirmed that this method works, I do recommend putting this as a on/off setting if this does work. Not all users will like it but it’s good for your eyes + feels nostalgic.

I'll try it out today and see if it works, thanks

**Comment by arichorn** [comment]
No problem!

**Comment by arichorn** [comment]
I’m guessing it didn’t work, it’s obvious when YouTube Music doesn’t have PageStyle implemented in their code (PageStyle is pretty much a thing for light mode & dark mode on the yt app)

**Comment by ginsudev** [comment]
It works, but only for the tab bar and nothing else. Is that the desired effect?

Also, there is pageStyle in YTMusic (Don't know if it's respected tho because the app only has dark mode).

**Comment by arichorn** [comment]
and alright I did try to modify it myself, it only effects the tab bar even if I added other Text UI Elements from YTCommonColorPalette/YTColorPalette, if I’ve seen all of YouTube Music Headers maybe I can find an alternative solution for this?

**Comment by ginsudev** [comment]
Got low contrast mode fully working. It'll be part of the next version

**Comment by arichorn** [comment]
Wait I’m impressed that you did that, my version in my repo just doesn’t effect anything even if I added other UIColor stuff to it, good job 👍

**Comment by arichorn** [comment]
I can’t believe that this got successfully added both YouTube Versions! 
Note: Google should’ve added the options to revert them in the first place but Google is ignorant and stubborn. 

YouTube (arichorn/uYouPlusExtra v17.40.5-2.1)
![43C66DBB-504B-4002-BFE3-A1D6DBD6EDDA](https://user-images.githubusercontent.com/78001398/196010696-2824f59b-8099-4e4a-87a9-d87dd1be77e5.jpeg)

YouTube Music (ginsudev/YTMusicUlitimate v1.2.5-Preview)
![E3B722CC-B4FA-4F5A-8D50-41A195C45345](https://user-images.githubusercontent.com/78001398/196010690-413faec2-a294-4207-bbd2-7dbaf4679040.jpeg)

**Comment by ginsudev** [comment]
3 Hooks in total ;)

v1.2.5 coming today / in a few hours

![image](https://user-images.githubusercontent.com/25361391/196011200-d3a70d76-0805-4cb5-8ade-1a4fe849d813.png)

**Comment by arichorn** [comment]
Woah. Didn’t think YouTube Music’s version was harder then it looks, but hey. At least we can toggle it in YTMusicUltimate! You did great work ginsudev, at least I helped a bit!
when this does release I will also implement some of the hooks from this one to the Normal YouTube if it supports PageStyle.

**Comment by arichorn** [comment]
It works great on YT Music! I’ve been trying to use this on normal YouTube because I always hated how it looked on the normal app, it’s because it doesn’t work on texts and iSponsorBlock button and your hook UIColor unfortunately doesn’t work with PageStyle. But it’s alright, your version is way better ☝️💖

**Comment by ginsudev** [comment]
Should be pretty easy to make it work with pageStyle. However checking pageStyle on YTMusic isn't needed so I didn't bother haha

**Comment by arichorn** [comment]
I did that and it gave me this https://github.com/arichorn/uYouPlusExtra/actions/runs/3259963270
I copied the page style code at the top so I don’t know if that hook supports page style
