### ISSUE TITLE
v1.3.5 doesn't install using signulous

### ISSUE THREAD

**Issue by ttyman0109a** [ginsudev/YTMusicUltimate#91]
Cannot install v1.3.5 using signulous.  It gets the generic app icon.  v1.3.4 installs just fine though.

**Comment by dayanch96** [comment]
The problem might be in your signing service.

**Comment by ttyman0109a** [comment]
Thanks for replying.  Nothing I can do.  I have installed 1.3.4 for now since that works.

**Comment by dayanch96** [comment]
> Thanks for replying. Nothing I can do. I have installed 1.3.4 for now since that works.

Ill mention you here with next update. Trying to fix small bugs

**Comment by ttyman0109a** [comment]
Thank you.

**Comment by ttyman0109a** [comment]
v1.3.6 still doesn't install using signulous

**Comment by ttyman0109a** [comment]
I guess there are no plans to fix it?  v1.3.4 and below used to work.  What signing service do you recommend then?

**Comment by ttyman0109a** [comment]
Could you look into it?  Something might have changed as v1.3.4 works with signulous and IPA app signer.  Thanks

**Comment by dayanch96** [comment]
Take a look: https://github.com/ginsudev/YTMusicUltimate/releases/tag/v1.3.7

**Comment by ttyman0109a** [comment]
Signed using IPA app signer and installed using XCode.  Thank you for fixing it.

**Comment by dayanch96** [comment]
Np. Feel free to re-open if you'll have any questions
