### ISSUE TITLE
Error installing version 1.3.5 using AltStore

### ISSUE THREAD

**Issue by bpavlov** [ginsudev/YTMusicUltimate#93]
When I try to sideload version 1.3.5 (and even 1.3.4) via AltStore I am getting this error:

Invalid value of WKCompanionAppBundleIdentifier key in WatchKit 2.0 app's Info.plist: com.google.ios.youtubemusic (expected com.google.ios.youtubemusic.XXXXXXX)

I tried several times (with/without extensions).

**Comment by getBoolean** [comment]
It just crashes AltStore for me, no error message (even without extensions). The latest version I was able to get sideloaded was 1.2.7

**Comment by billza7** [comment]
1. On your Mac, change the .ipa to .zip and confirm. 
2. Open the zip folder, you'll find a single app
3. Right click and choose "Show package contents"
4. Search for "Watch" in the search box and delete everything watch-related.
5. Go back and change .zip back to .ipa
6. Sideload as usual

**Comment by getBoolean** [comment]
> 1. On your Mac, change the .ipa to .zip and confirm.
> 2. Open the zip folder, you'll find a single app
> 3. Right click and choose "Show package contents"
> 4. Search for "Watch" in the search box and delete everything watch-related.
> 5. Go back and change .zip back to .ipa
> 6. Sideload as usual

Thanks, that worked.

**Comment by bpavlov** [comment]
Thank you. That worked.

**Comment by l-laziz** [comment]
@billza7 for the step 

> 1. On your Mac, change the .ipa to .zip and confirm.
> 2. Open the zip folder, you'll find a single app
> 3. Right click and choose "Show package contents"
> 4. Search for "Watch" in the search box and delete everything watch-related.
> 5. Go back and change .zip back to .ipa
> 6. Sideload as usual

For the step 5: can you clarify, do i compress back payload folder and rename it to .ipa or just rename original .zip folder which was extracted?

**Comment by billza7** [comment]
@l-laziz the latter
